'use client';

import { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/Button';

interface MobileHandoffProps {
  title: string;
  body: string;
  openOnPhone: string;
  copyLink: string;
  copied: string;
}

/**
 * The camera experience is deliberately mobile-first. On a desktop browser
 * the page still needs a useful, obvious entry point: this card hands the
 * exact public scan URL to a phone without requiring a login or a second app.
 *
 * The QR image is generated by a stateless public endpoint. The payload only
 * contains the public scan URL, never a session token or collection data. The
 * copy button remains the fallback when an extension, CSP or an offline phone
 * blocks the image request.
 */
export function MobileHandoff({
  title,
  body,
  openOnPhone,
  copyLink,
  copied,
}: MobileHandoffProps) {
  const [desktop, setDesktop] = useState(false);
  const [copiedState, setCopiedState] = useState(false);
  const [url, setUrl] = useState('');

  useEffect(() => {
    const media = window.matchMedia('(pointer: fine)');
    const update = () => setDesktop(media.matches && window.innerWidth >= 768);
    update();
    media.addEventListener('change', update);
    window.addEventListener('resize', update);
    setUrl(`${window.location.origin}${window.location.pathname}?mobile=1`);
    return () => {
      media.removeEventListener('change', update);
      window.removeEventListener('resize', update);
    };
  }, []);

  const qrUrl = useMemo(
    () =>
      url
        ? `https://api.qrserver.com/v1/create-qr-code/?size=240x240&margin=12&data=${encodeURIComponent(url)}`
        : '',
    [url],
  );

  if (!desktop || !url) return null;

  async function copy() {
    try {
      await navigator.clipboard.writeText(url);
      setCopiedState(true);
      window.setTimeout(() => setCopiedState(false), 1800);
    } catch {
      // The URL stays visible below the QR code, so clipboard permissions are
      // not a hard dependency for this handoff.
    }
  }

  return (
    <aside className="surface-flat flex flex-wrap items-center gap-4 rounded-[var(--radius-card)] p-4 sm:p-5">
      <div className="flex size-[152px] shrink-0 items-center justify-center rounded-xl bg-white p-2 shadow-sm">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={qrUrl} alt="" width={136} height={136} loading="lazy" />
      </div>
      <div className="min-w-[15rem] flex-1 space-y-2">
        <div className="flex items-center gap-2">
          <span aria-hidden className="text-sm text-azure">📱</span>
          <h2 className="text-[0.95rem] font-semibold">{title}</h2>
        </div>
        <p className="type-meta max-w-[52ch] text-[0.8rem]">{body}</p>
        <div className="flex flex-wrap gap-2 pt-1">
          <Button type="button" size="sm" variant="secondary" onClick={() => void copy()}>
            <span aria-hidden className="mr-1.5">⧉</span>
            {copiedState ? copied : copyLink}
          </Button>
          <a href={url} target="_blank" rel="noreferrer" className="inline-flex">
            <Button type="button" size="sm" variant="ghost">
              <span aria-hidden className="mr-1.5">↗</span>
              {openOnPhone}
            </Button>
          </a>
        </div>
        <p className="break-all font-mono text-[0.65rem] text-faint">{url}</p>
      </div>
    </aside>
  );
}
